# Generated by Django 3.2.16 on 2022-10-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
